name: omega_irc
description: A starting point for Dart libraries or applications.
version: 0.0.1-alpha
homepage: https://github.com/superlinkx/omega_irc

environment:
  sdk: ">=2.8.2 <3.0.0"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
